language: android

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/

sudo: false

jdk:
- oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - doc-28

script:
- ./gradlew clean test --parallel --stacktrace --no-daemon

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2/repository